FROM NODE:24-alpine AS builder
WORKDIR /app

# Buscaos los jsons
COPY package*.json .
COPY tsconfig*.json .

RUN npm install
COPY . .
RUN npm run build

FROM NODE:24-alpine AS runner
WORKDIR /app

COPY package*.json .
RUN npm ci --only=production

COPY --from=builder /app/dist ./dist
USER node

EXPOSE 3000

CMD ["npm" , "run", "start:prod"]